sudo: required
services:
  - docker 

before_install:
  - docker build -t 65avdc8654pr/docker-react -f Dockerfile.dev .

script:
  - docker run 65avdc8654pr/docker-react npm run test -- --coverage

# AWS Deployment Details
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker"
#   on:
#     branch: main
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key:
#       secure: "$AWS_SECRET_KEY"