sudo: required
services:
  - docker


before_install: 
  - docker build -t 65avdc8654pr/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run 65avdc8654pr/react-test npm test -- --coverage

after_success: 
  - docker build -t 65avdc8654pr/multi-client ./client
  - docker build -t 65avdc8654pr/multi-nginx ./nginx
  - docker build -t 65avdc8654pr/multi-server ./server
  - docker build -t 65avdc8654pr/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 65avdc8654pr/multi-client
  - docker push 65avdc8654pr/multi-server
  - docker push 65avdc8654pr/multi-nginx
  - docker push 65avdc8654pr/multi-worker

  # take those images and push them to docker hub
